import type { Patient, PatientStats } from "@/types/patient";

/**
 * Mock patient database based on the Stitch UI/UX design.
 */
const MOCK_PATIENTS: readonly Patient[] = [
  {
    id: "1",
    name: "Ahmad Nurrahman",
    age: 54,
    gender: "Laki-laki",
    status: "Aktif",
    lastActive: "Hari ini, 09:24",
    initials: "AN",
    whatsapp: "0811-9921-001",
    height: 170,
    weight: 72,
    bloodType: "A",
    registeredAt: "12 Jan 2023",
    compliance: 90,
    interventionType: "Mobile App",
    diabetesType: "Diabetes Tipe 2",
    doctor: "Dr. Ahmad Faisal",
    puskesmas: "Puskesmas Kuta Alam",
    address: "Jl. Diponegoro No. 45, Banda Aceh",
    email: "ahmad.nur@gmail.com",
    accountStatus: "Terverifikasi",
    nik: "1171011204720001",
    bpjs: "0001248593851",
    emergencyName: "Fatimah Nurrahman",
    emergencyRelation: "Istri",
    emergencyPhone: "0811-9921-002",
  },
  {
    id: "2",
    name: "Siti Maryam",
    age: 42,
    gender: "Perempuan",
    status: "Aktif",
    lastActive: "Kemarin",
    initials: "SM",
    whatsapp: "0812-3456-7890",
    height: 158,
    weight: 62,
    bloodType: "O",
    registeredAt: "01 Sep 2023",
    compliance: 85,
    interventionType: "Mobile App",
    diabetesType: "Diabetes Tipe 2",
    doctor: "Dr. Ahmad Faisal",
    puskesmas: "Puskesmas Kuta Alam",
    address: "Jl. T. Nyak Arief No. 123, Banda Aceh",
    email: "siti.maryam@gmail.com",
    accountStatus: "Terverifikasi",
    nik: "1171010109840002",
    bpjs: "0001248593852",
    emergencyName: "Budi Amin",
    emergencyRelation: "Suami",
    emergencyPhone: "0812-9900-1122",
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBonHLOi4DDR8Fl6O72N8wIWCIp9Ym2wPa1_3ST_Z2K8fJvYa2863-5Y0LRfVmavV-p0Fy0LS2-oH461IazfxZAiYY0BcqzJt-7gpWA0dTtpkAPKJ53BIDfL_TYSca0G0KHXKr97AfLSZ_RW1Q6GG5U6nKnAMo-NEVKQwqllgbhO0cgm80p2sM0RyTeBI6KTWOyMGI6zXUJokQOJlsBSxGG9FEtglu-HJ8fRF0thI6vI48rloIsrpsyQ2urYhat0TddrT4iOpvIpLYD",
  },
  {
    id: "3",
    name: "Bambang Kusuma",
    age: 61,
    gender: "Laki-laki",
    status: "Nonaktif",
    lastActive: "3 hari lalu",
    initials: "BK",
    whatsapp: "0813-8822-003",
    height: 165,
    weight: 68,
    bloodType: "B",
    registeredAt: "15 Apr 2023",
    compliance: 60,
    interventionType: "Web App",
    diabetesType: "Diabetes Tipe 1",
    doctor: "Dr. Sarah Amanda",
    puskesmas: "Puskesmas Baiturrahman",
    address: "Jl. Gajah Mada No. 12, Banda Aceh",
    email: "bambang.k@gmail.com",
    accountStatus: "Menunggu",
    nik: "1171011506650003",
    bpjs: "0001248593853",
    emergencyName: "Hendrawan Kusuma",
    emergencyRelation: "Anak Kandung",
    emergencyPhone: "0813-8822-004",
  },
  {
    id: "4",
    name: "Farah Hani",
    age: 38,
    gender: "Perempuan",
    status: "Aktif",
    lastActive: "05 Okt 2023",
    initials: "FH",
    whatsapp: "0815-7733-004",
    height: 160,
    weight: 55,
    bloodType: "AB",
    registeredAt: "10 Okt 2022",
    compliance: 95,
    interventionType: "Mobile App",
    diabetesType: "Diabetes Gestasional",
    doctor: "Dr. Ahmad Faisal",
    puskesmas: "Puskesmas Syiah Kuala",
    address: "Jl. Teuku Umar No. 88, Banda Aceh",
    email: "farah.hani@gmail.com",
    accountStatus: "Terverifikasi",
    nik: "1171012210880004",
    bpjs: "0001248593854",
    emergencyName: "Rudi Hartono",
    emergencyRelation: "Suami",
    emergencyPhone: "0815-7733-005",
  },
  {
    id: "5",
    name: "Siti Aminah",
    age: 62,
    gender: "Perempuan",
    status: "Aktif",
    lastActive: "Hari ini, 08:15",
    initials: "SA",
    whatsapp: "0812-3456-7890",
    height: 158,
    weight: 62,
    bloodType: "O",
    registeredAt: "12 Jan 2023",
    compliance: 85,
    interventionType: "Mobile App",
    diabetesType: "Diabetes Tipe 2",
    doctor: "Dr. Ahmad Faisal",
    puskesmas: "Puskesmas Kuta Alam",
    address: "Jl. T. Nyak Arief No. 123, Banda Aceh",
    email: "sitiaminah@gmail.com",
    accountStatus: "Terverifikasi",
    nik: "1171010109610005",
    bpjs: "0001248593855",
    emergencyName: "Budi Amin",
    emergencyRelation: "Suami",
    emergencyPhone: "0812-9900-1122",
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBonHLOi4DDR8Fl6O72N8wIWCIp9Ym2wPa1_3ST_Z2K8fJvYa2863-5Y0LRfVmavV-p0Fy0LS2-oH461IazfxZAiYY0BcqzJt-7gpWA0dTtpkAPKJ53BIDfL_TYSca0G0KHXKr97AfLSZ_RW1Q6GG5U6nKnAMo-NEVKQwqllgbhO0cgm80p2sM0RyTeBI6KTWOyMGI6zXUJokQOJlsBSxGG9FEtglu-HJ8fRF0thI6vI48rloIsrpsyQ2urYhat0TddrT4iOpvIpLYD",
  },
];

export const patientService = {
  /** Fetch all patients (simulated asynchronous call). */
  async getPatients(): Promise<Patient[]> {
    await new Promise((r) => setTimeout(r, 400));
    return [...MOCK_PATIENTS];
  },

  /** Fetch a specific patient by ID. */
  async getPatientById(id: string): Promise<Patient | null> {
    await new Promise((r) => setTimeout(r, 300));
    const patient = MOCK_PATIENTS.find((p) => p.id === id);
    return patient ?? null;
  },

  /** Fetch statistics summary for the patient metrics. */
  async getPatientStats(): Promise<PatientStats> {
    await new Promise((r) => setTimeout(r, 450));
    return {
      totalPatients: 1284,
      activePatients: 942,
      averageAge: 48,
    };
  },
} as const;
